version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-web
    ports:
      - "8081:80" #8080  is taken
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql
    container_name: restaurant-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password #better : ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prices_db
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
